name: 'Coverage'
description: 'Publish diff coverage report as PR comment'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.GITHUB_TOKEN }} | gh auth login --with-token
      shell: bash
    - run: echo "AAAA" && gh repo view && echo "BBBB"
      shell: bash
